### PR TITLE
Improved: PurchaseOrders, Returns, Shipments page with autofocus on searchbar(#2vd9jaf)

### LINKED ISSUE #133: Enable auto-focus on actionable content for all the pages
## What is the motivation for adding/enhancing this feature?

This feature will help the users to easily navigate through the app

## What are the acceptance criteria?

- [ ] The input fields and buttons should be in focus on tab key
- [ ] When searched for specific string, if some data found then the first item in the list should be in focus

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by shashwatbangar**
### Related Issues

Closes #133 

### Short Description and Why It's Useful

Whenever someone will open PurchaseOrders, Returns or Shipments page, searchbar will be in focus automatically, also tab indexing is working, if we press tab when focused on searchbar, focus will move to products lists & on pressing enter we can move to details page respectively.

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/62360781/192787972-966778be-8594-42fa-b330-952a71fd2c24.mov

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

**Comment by adityasharma7** [comment]
@shashwatbangar 

We could check for possibility with below solution
https://stackoverflow.com/a/66869477/7130371

**Comment by shashwatbangar** [comment]
> @shashwatbangar
> 
> We could check for possibility with below solution https://stackoverflow.com/a/66869477/7130371

I checked it sir, Not working.

**Comment by adityasharma7** [comment]
Check with Ionic lifecycle hooks:
https://ionicframework.com/docs/vue/lifecycle

**Comment by k2maan** [comment]
Focus using nextTick doesn't work, even with Ionic lifecycle hooks.

**Comment by k2maan** [comment]
Checked with Ionic lifecycle hooks, it doesn't seem to work.

**Pull request closed without merging**
